### ISSUE TITLE
rosidl_generator_py build flaky on the farm

### ISSUE THREAD

**Issue by wjwwood** [ros2/rosidl#110]
See: http://ci.ros2.org/job/ci_linux/1077/console

It looks like there is a missing make dependency, so sometimes when building in parallel you get an out of order build which fails.

**Comment by jacquelinekay** [comment]
Is this still an issue?

**Comment by mikaelarguedas** [comment]
I didn't see it in any of the recent jobs. Maybe is has been fixed [here](https://github.com/ros2/rosidl/pull/111) ?

**Comment by jacquelinekay** [comment]
I would advocate closing this issue until we see it again (which hopefully won't happen). It does look like it was fixed in that patch. @dirk-thomas do think this is closable?

**Comment by dirk-thomas** [comment]
I assume it has been fixed by #111 and I haven't seen it since then.
