### ISSUE TITLE
Python generator called repeatedly in message interface packages

### ISSUE THREAD

**Issue by jacquelinekay** [ros2/rosidl#124]
The message "Generating Python code for ROS interfaces" is printed repeatedly during compilation of message interface packages. It seems the Python generator is being called repeatedly when it should only be called once.

**Comment by dirk-thomas** [comment]
The code generation is also being retriggered during the installation step which rebuilds the code again.

**Comment by mikaelarguedas** [comment]
#125 has fixed the multiple invocations of the python generator for Linux and OSX. It seems that on windows only the install step is fixed, the generator is still called multiple times during the build step.

**Comment by dirk-thomas** [comment]
Do you have a link to a Jenkins job which shows that behavior?

**Comment by mikaelarguedas** [comment]
This happens only on windows builds: http://ci.ros2.org/job/ci_windows/1268/
It may be linked to the fact the PythonExtra module cannot be found on windows because PEP-3149 doesn't specify anything for python extension suffixes on windows.
I haven't looked into it yet, I just noticed it on my CI jobs last night

**Comment by dirk-thomas** [comment]
This referenced build is 8 days old so not really saying much. But a current build of master shows the same problem: http://ci.ros2.org/job/ci_windows/1295/consoleFull (search for "Generating Python", twice per package). There I will reopen this.

**Comment by mikaelarguedas** [comment]
sorry messed up my copy paste. I was referring to the CI job of my last PR: http://ci.ros2.org/job/ci_windows/1294. But yeah same issue on current master.

**Comment by mikaelarguedas** [comment]
Seems to be a cmake issue @dirk-thomas contacted kitware to find a solution/workaroud

**Comment by dirk-thomas** [comment]
Still waiting for a feedback from Kitware / Microsoft on this.
