### ISSUE TITLE
[rosidl_generator_py] Provide field type in the generated message classes

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/rosidl#243]
#### Feature description

If a message has fields that are arrays (Bounded or Unbounded), there is no way for an external tool to get the relevant information as of what type the fields of this array are supposed to be. 

#### Implementation considerations

A suggested approach is to extend the generated message class to provide the type of the various fields. This information could then be leveraged by a higher level function/utility (in rclpy ?) that could fill a message based on user specified values. 

connects to ros2/ros2cli#59
necessary to fix ros2/ros2cli#59

**Comment by dirk-thomas** [comment]
Closing in favor of ros2/rosidl_python#16.
