### ISSUE TITLE
[rosidl_generator_cpp] add <<operator for message classes

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/rosidl#259]
We should provide a `<<operator` like in ROS 1 to ease printing to streams. Some places in the codebase print manually message content to stream in the meantime, e.g. https://github.com/ros2/demos/blob/144fb6d80810f149fa2457ae8542b332a6497674/demo_nodes_cpp/src/parameters/parameter_events.cpp#L26

**Comment by mikaelarguedas** [comment]
this will require a decision on what format (YAML, JSON, something else?) we want for the output. 
Other PR related to the formats chosen: https://github.com/ros2/rclcpp/pull/275

**Comment by dirk-thomas** [comment]
The decision from the last conversation on this topic was to *not* create such operators. Instead there should be global functions specialized on the message named `to_yaml` / `to_json` / `to_whatever_you_like`.

**Comment by wjwwood** [comment]
I didn't think that we ruled out an `operator<<` which defaulted to one of those, for convenience.
