### ISSUE TITLE
Building multiple interfaces in the same CMake context messes up the build order

### ISSUE THREAD

**Issue by kutschkem** [ros2/rosidl#267]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  - binary
- Version or commit hash:
  -  release-ardent-20180307
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

[testBuild.tar.gz](https://github.com/ros2/rosidl/files/1871490/testBuild.tar.gz)

See attached test project. Build the attached test project in /testBuild with 

```
mkdir build
cd build
cmake .. -DAMENT_CMAKE_UNINSTALL_TARGET=OFF 
make
```

The testproject contains two message packages which each build on their own, but when build in combination (via add_subdirectory) produce the error mentioned below.

#### Expected behavior
Interfaces get generated.

#### Actual behavior
Build order is messed up, this is the output when the test project is built:

> Scanning dependencies of target matrix2_ros
> [  2%] Building CXX object CMakeFiles/matrix2_ros.dir/src/main.cpp.o
> [  4%] Linking CXX executable matrix2_ros
> [  4%] Built target matrix2_ros
> Scanning dependencies of target matrix2_msgs__py
> [  6%] Generating Python code for ROS interfaces
> [  6%] Built target matrix2_msgs__py
> [  8%] Generating C code for ROS interfaces
> Scanning dependencies of target matrix2_msgs__rosidl_generator_c
> [  8%] Generating C code for ROS interfaces
> [ 10%] Building C object implementation/CMakeFiles/matrix2_msgs__rosidl_generator_c.dir/rosidl_generator_c/matrix2_msgs/msg/mat__functions.c.o
> cc: error: /home/uidq3479/Jenkins/workspace/XCitDevelopment_PR-164-OI7ZPASJZEV3XGQWBFQY2PEQXIELKYENI5G6JZQZXQR3CPC6F5NA/tests/eclipseProject/algos/matrix/testing/testbuild/build/implementation/rosidl_generator_c/matrix2_msgs/msg/mat__functions.c: Datei oder Verzeichnis nicht gefunden
> 

Apparently necessary source files are not generated prior to compilation.

#### Additional information

I understand that building multiple packages in the same context is suboptimal, but feel like I am still within the bounds of what should work. If not, please advise me on how to properly implement multipackage builds that also need to work with non-ament parts of the build.

**Comment by dirk-thomas** [comment]
The internally generated files assume that they are being invoked only once per CMake context. I have created #268 as well as the referenced PRs in that ticket for this specific case. With these patches your example should build fine.

I just want to mention again that this is outside of our normal usage and it is likely that you will run into more issues like that. Please feel free to make similar PRs when it enables your use case.
