### ISSUE TITLE
Expose message field names in C++ code

### ISSUE THREAD

**Issue by sagniknitr** [ros2/rosidl#293]
## Feature request
Expose message field names in C++ code.
#### Feature description
We can have a function which can give the field names of a particular ros2 message.Currently we can do this in python, but I am not sure whether any C++ API for this exist.

#### Implementation considerations
Add function (like `std::vector<string> return_message_fields()`) in the empy template file , so that it can be generated for all the ros2 messages.

**Comment by dirk-thomas** [comment]
The [rosidl_typesupport_introspection_cpp](https://github.com/ros2/rosidl/tree/692b66b0128d1098b5052dc126dfb184a69c1c21/rosidl_typesupport_introspection_cpp) already provides that information (there is a C equivalent to). It not only provides the field name but also all the information about the types, array sizes, upper boundaries, etc. Basically all the information from the `.msg` file (except the comments at the moment).
