### ISSUE TITLE
support for WString across all generators

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rosidl#352]
Follow up of ros2/rosidl#346.

**Comment by dirk-thomas** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6895)](http://ci.ros2.org/job/ci_linux/6895/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3173)](http://ci.ros2.org/job/ci_linux-aarch64/3173/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5661)](http://ci.ros2.org/job/ci_osx/5661/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6716)](http://ci.ros2.org/job/ci_windows/6716/)

**Comment by jacobperron** [comment]
Looks like you've addressed all the warnings/failures. Considering you are adding more work on top of this, we can merge as-is and catch anything we missed in the next round of CI.

**Comment by dirk-thomas** [comment]
I went over all PRs again and resolved the remaining comments. In favor of time I will merge the changes now and trigger a set of CI builds afterwards to double check. :crossed_fingers:
