### ISSUE TITLE
[Feature Request] Initialize generic typesupport_introspection_cpp message

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rosidl#404]
There is currently code available within the rosbag packages, which allows to [allocate memory for a ROS2 message given the introspection typesupport](https://github.com/ros2/rosbag2/blob/b7ed595d130b90afc652538c33ce02d5e73f1064/rosbag2/src/rosbag2/types/introspection_message.cpp#L29-L47).

This is essentially nothing else than iterating over the typesupport and respectively allocate individually fields. This essentially allows to allocate a ROS2 message with the same memory layout as a regularly created ROS2 message without requiring a compile time available template.

While this was working fine for rosbags, we realized that this is being used in other rmw implementations as well and I am wondering if this repo is a suited place to move this piece of code into.

---

Edit: Changing the title to request initialization only. The memory for the actual message can be allocated outside of the typesupport (either in a memory pool, or shared memory, or simply with `malloc/new`). The important part here is to run a constructor/init and destructor/fini function on that piece of memory.

**Comment by dirk-thomas** [comment]
> we realized that this is being used in other rmw implementations as well 

Can you please reference these for context.

**Comment by Karsten1987** [comment]
one of them being [fastrtps_dynamic](https://github.com/ros2/rmw_fastrtps/blob/master/rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp)

**Comment by dirk-thomas** [comment]
The referenced function doesn't seem to allocate a message but only populate a given message pointer with data?
