### ISSUE TITLE
Should rosidl_generator_c be a rosidl_runtime_packages?

### ISSUE THREAD

**Issue by ahcorde** [ros2/rosidl#437]
`rosidl_generator_c` is not a member of **rosidl_runtime_packages** but `rosidl_generator_cpp` is a member of **rosidl_runtime_packages**

Not sure about why this is like this, any thoughts @wjwwood ?

**Comment by wjwwood** [comment]
I don't, it seemed fishy to me though. Maybe you can do a bit more research into when `rosidl_generator_cpp` was added and why the c version was not.

@dirk-thomas may have some insight as well.

**Comment by dirk-thomas** [comment]
It probably should be listed as a explicit dependency in `rosidl_runtime_packages` for consistency. Since the C++ as well as the Python generators both already export a dependency on `rosidl_generator_c` it won't make a difference though.

**Comment by ahcorde** [comment]
closing this, Fixed in this PR https://github.com/ros2/rosidl/pull/440/files
