### ISSUE TITLE
Splitted rosidl_generator_c and rosidl_generator_cpp in two: rosidl_generator_x and rosidl_runtime_x

### ISSUE THREAD

**Issue by ahcorde** [ros2/rosidl#443]
This issue is to track all the PRs that are need it to compile ros2.repos with the changes introduced in this PR split https://github.com/ros2/rosidl/pull/442. We will have these packages:

 - rosidl_generator_c
 - rosidl_generator_cpp 
 - rosidl_runtime_c (new)
 - rosidl_runtime_cpp (new)

**Comment by ahcorde** [comment]
- [ ] https://github.com/ros2/rmw_cyclonedds/pull/110
 - [ ] https://github.com/ros2/rmw_opensplice/pull/303
 - [ ] https://github.com/ros2/rmw_fastrtps/pull/351
 - [ ] https://github.com/ros2/rmw_implementation/pull/86
 - [ ] https://github.com/ros2/rosidl_python/pull/100
 - [ ] https://github.com/ros2/rosidl_typesupport_fastrtps/pull/32
 - [ ] https://github.com/ros2/rosidl_typesupport/pull/58
 - [ ] https://github.com/ros2/rosbag2/pull/310
 - [ ] https://github.com/ros2/rosidl_defaults/pull/4

**Comment by dirk-thomas** [comment]
It would make it easier to review these PRs if you could reference at least one specific source line in the packages where new dependencies are added to clarify why they are added. It might also be good to clarify - when runtime packages are added - why generators are still needed.

**Comment by ahcorde** [comment]
> It might also be good to clarify - when runtime packages are added - why generators are still needed.

This was my fault I didn't remove the rosidl_generator_c/cpp dependencies. I revisited all the changes and removed this dependencies

**Comment by ahcorde** [comment]
I have been checking rcl, rcl_lifecycle, rcl_action, rclcpp and rclcpp_action all of them make use of rosidl_generator ( with the new packages should be rosidl_runtime) but I think this dependecy is not need it, the reason why it's because rosidl_generator/rosidl_runtim is used where a message packages it's being used too.

Some examples:
RCL:
https://github.com/ros2/rcl/blob/master/rcl_action/CMakeLists.txt#L57
https://github.com/ros2/rcl/blob/master/rcl_lifecycle/CMakeLists.txt#L48

RCLCPP:

https://github.com/ros2/rclcpp/blob/master/rclcpp_action/CMakeLists.txt#L36
https://github.com/ros2/rclcpp/blob/master/rclcpp/CMakeLists.txt#L180

@wjwwood and @dirk-thomas what do you think?

**Comment by ahcorde** [comment]
testing all PRs

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9748)](http://ci.ros2.org/job/ci_linux/9748/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5373)](http://ci.ros2.org/job/ci_linux-aarch64/5373/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7922)](http://ci.ros2.org/job/ci_osx/7922/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9619)](http://ci.ros2.org/job/ci_windows/9619/)

**Comment by ahcorde** [comment]
- [ ] https://github.com/ros2/rmw_connext/pull/399
 - [ ] https://github.com/ros2/rosidl_typesupport_connext/pull/49

**Comment by ahcorde** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9758)](http://ci.ros2.org/job/ci_linux/9758/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5381)](http://ci.ros2.org/job/ci_linux-aarch64/5381/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7930)](http://ci.ros2.org/job/ci_osx/7930/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9627)](http://ci.ros2.org/job/ci_windows/9627/)

**Comment by dirk-thomas** [comment]
Please double check that with all the PRs the actual goal (avoiding a runtime dependency on any generator package) has been achieved.

**Comment by ahcorde** [comment]
`rmw_connext` and `rosidl_typesupport_connext` approved. Launching CI for all the commits:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9786)](http://ci.ros2.org/job/ci_linux/9786/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5408)](http://ci.ros2.org/job/ci_linux-aarch64/5408/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7953)](http://ci.ros2.org/job/ci_osx/7953/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9649)](http://ci.ros2.org/job/ci_windows/9649/)

**Comment by ahcorde** [comment]
I have been reproducing the failure in my local MAC OS machine. if I used `include_directories` there is no issue when cmake is trying to find the generated headers, but with `target_include_directories`, I think a race condition is happening. If I execute colcon a second time then the error disappears.

@wjwwood or @dirk any thoughts about this?

**Comment by dirk-thomas** [comment]
The `rosidl_generator_cpp` PR removes the `add_dependencies(<test_target> ${PROJECT_NAME})` calls for all test targets: e.g. https://github.com/ros2/rosidl/pull/442/files#diff-59c331d207ef4d5e6a390e74e0bc4739L54

Without that dependency CMake tries to build the test before the code generator was run which creates the used header files.

**Comment by ahcorde** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9805)](http://ci.ros2.org/job/ci_linux/9805/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5426)](http://ci.ros2.org/job/ci_linux-aarch64/5426/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7973)](http://ci.ros2.org/job/ci_osx/7973/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9667)](http://ci.ros2.org/job/ci_windows/9667/)

**Comment by ahcorde** [comment]
The packages depend on `rosidl_generator_c` or `rosidl_generator_cpp` are:
 - rosidl_typesupport_introspection_cpp
 - rosidl_typesupport_introspection_c
 - rosidl_default_generators

The packages depend on `rosidl_runtime_c` or `rosidl_runtime_cpp`

 - rmw_cyclonedds
 - rmw_fastrtps
 - rmw
 - rosidl_python
 - rosidl_typesupport_fastrtps
 - rosidl_typesupport
 - rosbag2
 - rosidl_defaults
 - rclcpp
 - rcl

**Comment by dirk-thomas** [comment]
> The packages depend on rosidl_generator_c or rosidl_generator_cpp are:

I guess the dependencies still need to be removed from the two introspection packages then to achieve the stated goal, right?

**Comment by ahcorde** [comment]
- Removed `rosidl_generator_c`  and `rosidl_generator_cpp` from `rosidl_typesupport_introspection_cpp` and `rosidl_typesupport_introspection_c`.
 - Added `rosidl_generator_c`  and `rosidl_generator_cpp` to `rosidl_generator_py`

------

The packages depend on `rosidl_generator_c` or `rosidl_generator_cpp` are:
 - rosidl_default_generators
 - rosidl_generator_py

The packages depend on `rosidl_runtime_c` or `rosidl_runtime_cpp`

 - rmw_cyclonedds
 - rmw_fastrtps
 - rmw
 - rosidl_python
 - rosidl_typesupport_fastrtps
 - rosidl_typesupport
 - rosidl_typesupport_introspection_cpp
 - rosidl_typesupport_introspection_c
 - rosbag2
 - rosidl_defaults
 - rclcpp
 - rcl

**Comment by ahcorde** [comment]
- [ ] https://github.com/ros2/rmw_dds_common/pull/10

**Comment by ahcorde** [comment]
The packages depend on `rosidl_generator_c` or `rosidl_generator_cpp` are:

- rmw_dds_common_generators
- rosidl_default_generators
- rosidl_generator_py

The packages depend on `rosidl_runtime_c` or `rosidl_runtime_cpp`

- rcl
- rclcpp
- rmw
- rmw_cyclonedds
- rmw_dds_common
- rmw_fastrtps
- rosbag2
- rosidl_defaults
- rosidl_python
- rosidl_typesupport
- rosidl_typesupport_fastrtps
- rosidl_typesupport_introspection_c
- rosidl_typesupport_introspection_cpp

**Comment by dirk-thomas** [comment]
Please update all PRs to update / revert changes to dependency types of the follow kind, e.g. ros2/rmw_dds_common#10:

Since the added `buildtool_depend` and `buildtool_export_depend` dependencies are a build as well as a run dependency please revert the dependency type to the previously used `depend`. I would rather like to avoid that kind of dependency type changes in this already massive amount of changes.

**Comment by dirk-thomas** [comment]
Also please update the list of all related PRs somewhere in this ticket.

**Comment by ahcorde** [comment]
The packages depend on `rosidl_generator_c` or `rosidl_generator_cpp` are:

- rmw_dds_common_generators https://github.com/ros2/rmw_dds_common/pull/10
- rosidl_default_generators https://github.com/ros2/rosidl_defaults/pull/5
- rosidl_generator_py https://github.com/ros2/rosidl_python/pull/100

The packages depend on `rosidl_runtime_c` or `rosidl_runtime_cpp`

- rcl https://github.com/ros2/rcl/pull/588
- rclcpp https://github.com/ros2/rclcpp/pull/1014
- rmw  https://github.com/ros2/rmw/pull/198
- rmw_cyclonedds https://github.com/ros2/rmw_cyclonedds/pull/138
- rmw_dds_common https://github.com/ros2/rmw_dds_common/pull/10
- rmw_conenxt https://github.com/ros2/rmw_connext/pull/399
- rmw_fastrtps https://github.com/ros2/rmw_fastrtps/pull/351
- rosbag2 https://github.com/ros2/rosbag2/pull/310
- rosidl  https://github.com/ros2/rosidl/pull/442
  - rosidl_runtime_c
  - rosidl_runtime_cpp
  - rosidl_typesupport_introspection_c
  - rosidl_typesupport_introspection_cpp
- rosidl_defaults https://github.com/ros2/rosidl_defaults/pull/5
- rosidl_python https://github.com/ros2/rosidl_python/pull/100
- rosidl_typesupport https://github.com/ros2/rosidl_typesupport/pull/58
- rosidl_typesupport_connext https://github.com/ros2/rosidl_typesupport_connext/pull/49
- rosidl_typesupport_fastrtps https://github.com/ros2/rosidl_typesupport_fastrtps/pull/32


-------
## update / revert changes to dependency types

 - rmw_connext https://github.com/ros2/rmw_connext/pull/399/files
 - rosidl_typesupport_connext https://github.com/ros2/rosidl_typesupport_connext/pull/49/files
 - rosbag2 https://github.com/ros2/rosbag2/pull/310/files
 - rmw_fastrtps https://github.com/ros2/rmw_fastrtps/pull/351/files
 - rmw_dds_common https://github.com/ros2/rmw_dds_common/pull/10/files
 - rcl https://github.com/ros2/rcl/pull/588
 - rosidl_typesupport_fastrtps https://github.com/ros2/rosidl_typesupport_fastrtps/pull/32/files
 - rosidl https://github.com/ros2/rosidl/pull/442/files

**Comment by ahcorde** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9955)](http://ci.ros2.org/job/ci_linux/9955/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5562)](http://ci.ros2.org/job/ci_linux-aarch64/5562/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8099)](http://ci.ros2.org/job/ci_osx/8099/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9824)](http://ci.ros2.org/job/ci_windows/9824/)

**Comment by ahcorde** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9962)](http://ci.ros2.org/job/ci_linux/9962/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5567)](http://ci.ros2.org/job/ci_linux-aarch64/5567/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8105)](http://ci.ros2.org/job/ci_osx/8105/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9831)](http://ci.ros2.org/job/ci_windows/9831/)

**Comment by ahcorde** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9984)](http://ci.ros2.org/job/ci_linux/9984/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5584)](http://ci.ros2.org/job/ci_linux-aarch64/5584/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8123)](http://ci.ros2.org/job/ci_osx/8123/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9861)](http://ci.ros2.org/job/ci_windows/9861/)

**Comment by ahcorde** [comment]
These warnings on Windows were already fixed, but I didn't update the branch in the PR

```
15:49:21 C:\ci\ws\src\ros2\rmw_dds_common\rmw_dds_common\test\test_graph_cache.cpp(195,8): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\ci\ws\build\rmw_dds_common\test_graph_cache.vcxproj]

15:49:21 C:\ci\ws\src\ros2\rmw_dds_common\rmw_dds_common\test\test_graph_cache.cpp(388,8): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\ci\ws\build\rmw_dds_common\test_graph_cache.vcxproj]

```

**Comment by ahcorde** [comment]
Testing changes on rmw_cyclonedss

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10004)](http://ci.ros2.org/job/ci_linux/10004/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5604)](http://ci.ros2.org/job/ci_linux-aarch64/5604/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8139)](http://ci.ros2.org/job/ci_osx/8139/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9888)](http://ci.ros2.org/job/ci_windows/9888/)

**Comment by ahcorde** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10011)](http://ci.ros2.org/job/ci_linux/10011/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5612)](http://ci.ros2.org/job/ci_linux-aarch64/5612/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8148)](http://ci.ros2.org/job/ci_osx/8148/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9901)](http://ci.ros2.org/job/ci_windows/9901/)

**Comment by ahcorde** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10026)](http://ci.ros2.org/job/ci_linux/10026/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5622)](http://ci.ros2.org/job/ci_linux-aarch64/5622/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8157)](http://ci.ros2.org/job/ci_osx/8157/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9931)](http://ci.ros2.org/job/ci_windows/9931/)

**Comment by ahcorde** [comment]
- Updated all repos involved in this change. 
 - Skipping `ros1_bridge`, `qt_*`, `rqt_*`, and `rviz_*` packages. 
 - Testing against `test_rclcpp` and `rosbag2_tests`.

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10031)](http://ci.ros2.org/job/ci_linux/10031/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5626)](http://ci.ros2.org/job/ci_linux-aarch64/5626/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8161)](http://ci.ros2.org/job/ci_osx/8161/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9938)](http://ci.ros2.org/job/ci_windows/9938/)

**Comment by ahcorde** [comment]
- One warning made the builds unstable but there is a ([PR pending](https://gitlab.com/micro-ROS/ros_tracing/ros2_tracing/-/merge_requests/163))

In MacOS
 - projectroot.cppcheck

Windows
 - some failures in test_rclcpp

```
CMake Deprecation Warning at /home/jenkins-agent/workspace/ci_linux-aarch64/ws/install/ament_cmake_export_interfaces/share/ament_cmake_export_interfaces/cmake/ament_export_interfaces.cmake:37 (message):
ament_export_interfaces() is deprecated, use ament_export_targets() instead
Call Stack (most recent call first):
CMakeLists.txt:85 (ament_export_interfaces)
```
