### ISSUE TITLE
Progress toward Quality Level 1

### ISSUE THREAD

**Issue by Blast545** [ros2/rosidl#451]
This issue tracks the progression of packages in `rosidl` that have been deemed necessary for Quality Level 1 and a 1.0 version level. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/master/rep-2004.rst).

The packages slated for Quality Level 1 for ROS 2 Foxy are:
- rosidl_runtime_c
- rosidl_runtime_cpp
- rosidl_typesupport_interface

Excluded for Quality Level 1 at this time:
- rosidl_adapter
- rosidl_cmake
- rosidl_generator_c	
- rosidl_generator_cpp	
- rosidl_parser
- rosidl_typesupport_introspection_c
- rosidl_typesupport_introspection_cpp

# Progress common to all packages:
* [x] Version Policy
    - `semver` according to the recommendation for ROS Core packages in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#versioning).
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Recommended guidelines for ROS Core packages in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#package-requirements)
* [x] API and ABI stability within a ROS distribution
* [x] Quality Declaration document for each package
* [x] Vulnerability Disclosure Policy

Documentation
* [x] Declared set of licenses
* [x] Copyright statement in each source file
    - Checked with `ament_copyright`

Platform Support
* [x] Supports all tier 1 platforms as described in [REP-2000](https://www.ros.org/reps/rep-2000.html#support-tiers)

# Progress of specific packages
## rosidl_runtime_c
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API.
  - [x] Hosted

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
  - rosidl_typesupport_interface -> QL2
* [x] non-ROS dependencies are equivalent level 1
  - None

Testing:
* [x] Must have system tests which cover all items in the "feature" documentation
* [x] Must have system, integration, and/or unit tests which cover all of the public API
* [x] Code Coverage > 95%:
  - * [x] Must have code coverage tracking for the package -> [here](https://ci.ros2.org/job/ci_linux_coverage/lastSuccessfulBuild/cobertura/)
  - * [x] Must have and enforce a code coverage policy for new changes [Policy](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#code-coverage)
* [x] Performance tests: not currently available.
* [x] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it.
  - * [x] Must use static analysis tools where applicable: 
  -- See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

## rosidl_runtime_cpp
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
  - [x] Hosted
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
  - rosidl_typesupport_interface -> QL2
* [x] non-ROS dependencies are equivalent level 1
  - None

Testing:
* [x] Must have system tests which cover all items in the "feature" documentation
* [x] Must have system, integration, and/or unit tests which cover all of the public API
  - This package is mostly composed of types and functions that do not require testing.
* [x] Code Coverage > 95%:
  - * [x] Must have code coverage tracking for the package -> [Here](https://ci.ros2.org/job/ci_linux_coverage/lastSuccessfulBuild/cobertura/src_ros2_rosidl_rosidl_runtime_cpp_include_rosidl_runtime_cpp)
  - * [x] Must have and enforce a code coverage policy for new changes [Policy](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#coverage)
* [x] Performance:
  - * [x] Must have performance tests 
* [x] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it
  - * [x] Must use static analysis tools where applicable: 
  -- See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

## rosidl_typesupport_interface
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
  - [x] Hosted

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
  - None
* [x] non-ROS dependencies are equivalent level 1
  - None

Testing:
* [x] Must have system tests which cover all items in the "feature" documentation
* [x] Must have system, integration, and/or unit tests which cover all of the public API
* [x] Code Coverage:
  - * [x] Must have code coverage tracking for the package. Not needed, package defines C macro definitions.
  - * [x] Must have and enforce a code coverage policy for new changes [Policy](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#coverage)
* [x] Performance:
  - * [x] Must have performance tests 
* [x] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it
  - * [x] Must use static analysis tools where applicable: 
  -- See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

**Comment by chapulina** [comment]
@Blast545 , when the generators were split in 2 in https://github.com/ros2/rosidl/pull/442 we started focusing on the `rosidl_runtime_X` packages instead of the generators. Do you think you could add those to this issue? Their QDs are up-to-date for level 2 since #499 and #500, so this should be quick. Thanks!

**Comment by Blast545** [comment]
@chapulina done. I added a couple of extra links to be more clear about the statements of this issue. Let me know if you think this is fine, to update other issues with this format.

**Comment by chapulina** [comment]
Looks great, thanks!

**Comment by chapulina** [comment]
All 3 packages are level 1! :tada:
