### ISSUE TITLE
Update README for How to build rosidl/rosidl_adapter/ project to convert .msg file into idl format

### ISSUE THREAD

**Issue by neelamgunjal12** [ros2/rosidl#588]
I am beginner in this, trying to build package rosidl_adapter but not able to run the code. README is not updated for compilation steps for the particular project. Could anyone update REDME file for compilation steps with detailed description (for example what should be installed or command line argument list, etc) or share link if already available.

I am facing this issue as listed below. thinking due to wrong input
  File "__init__.py", line 20, in convert_msg_to_idl
    msg = parse_message_string(package_name, pathlib.Path(input_file).stem, content)
  File "/home/developer/Downloads/rosidl-master/rosidl_adapter/rosidl_adapter/msg/parser.py", line 539, in parse_message_string
    msg = MessageSpecification(pkg_name, msg_name, fields, constants)
  File "/home/developer/Downloads/rosidl-master/rosidl_adapter/rosidl_adapter/msg/parser.py", line 388, in __init__
    pkg_name + PACKAGE_NAME_MESSAGE_TYPE_SEPARATOR + msg_name)
  File "/home/developer/Downloads/rosidl-master/rosidl_adapter/rosidl_adapter/msg/parser.py", line 206, in __init__
    self.type, VALID_MESSAGE_NAME_PATTERN.pattern))
parser.InvalidResourceName: 'rosidl_adapter' is an invalid message name. It should have the pattern '^[A-Z][A-Za-z0-9]*$'

**Comment by clalancette** [comment]
You need to follow the instructions at https://docs.ros.org/en/foxy/Installation.html to build this project.  This isn't really meant to be a standalone project; it is part of the larger ROS 2 project.

In the future, please ask questions like this on https://answers.ros.org so we have all questions and answers in one easily searchable place.
