### ISSUE TITLE
Resolve dependencies correctly

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rosidl#59]
Remove the temporary hack from #58 and come up with the "correct" fix for the problem.

**Comment by wjwwood** [comment]
I suggest we keep https://github.com/ros2/ros2/issues/174 open (https://github.com/ros2/ros2/issues/174#issuecomment-165885946) and use it to track this.

**Comment by mikaelarguedas** [comment]
Closing this in favor of  ros2/ros2#174
