### ISSUE TITLE
Relocate `to_yaml()` definition to message namespace 

### ISSUE THREAD

**Issue by hidmic** [ros2/rosidl#607]
#### Feature description

Follow-up after #523. When `to_yaml()` function definitions were pushed into the `rosidl_generator_traits` namespace, argument-dependent lookups were blocked. This makes it difficult to use these overloads in templates -- all overloads must be visible to the compiler when it first hits the template definition for them to be picked up.

Relocating them would simplify their use.

**Comment by hidmic** [comment]
@sloretz @clalancette @ivanpauno thoughts?

**Comment by sloretz** [comment]
I don't understand - got an example code sample that works in plain code but not in a template?

**Comment by hidmic** [comment]
@sloretz see this quick and dirty [example](https://coliru.stacked-crooked.com/a/ad3167dd80a9a138) to show the problem with overloads and namespaces.

**Comment by sloretz** [comment]
Ah, meaning the problem is templates defined before the message's type traits header is included can't use `to_yaml(...)`? Is this what you mean by moving the definition to the message namespace?
https://coliru.stacked-crooked.com/a/fe75cd8807bd569d

**Comment by hidmic** [comment]
That's one option, but it doesn't have to be a method. https://coliru.stacked-crooked.com/a/9067c566be1f3097 would do as well and we wouldn't have to force formatting details into the `struct`.

**Comment by hidmic** [comment]
@sloretz thoughts?

**Comment by sloretz** [comment]
Seems reasonable to me! It looks like we could have it in both namespaces without too much trouble (https://coliru.stacked-crooked.com/a/d3f6151e3378f8a4), but it seems better to me to have only one way of calling the same thing.

**Comment by hidmic** [comment]
Yeah, we can keep it in `rosidl_generator_traits` to help deprecation. I'll send a patch.

**Comment by ivanpauno** [comment]
> That's one option, but it doesn't have to be a method. https://coliru.stacked-crooked.com/a/9067c566be1f3097 would do as well and we wouldn't have to force formatting details into the struct.

+1

> Seems reasonable to me! It looks like we could have it in both namespaces without too much trouble (https://coliru.stacked-crooked.com/a/d3f6151e3378f8a4), but it seems better to me to have only one way of calling the same thing.

+1

> Yeah, we can keep it in rosidl_generator_traits to help deprecation. I'll send a patch.

+1
