### ISSUE TITLE
‘to_yaml’ is not a member of ‘rosidl_generator_traits’

### ISSUE THREAD

**Issue by zazgf** [ros2/rosidl#631]
When I build autoware , I get error:‘to_yaml’ is not a member of ‘rosidl_generator_traits’.

**Comment by clalancette** [comment]
For questions like this, please use https://answers.ros.org, and make sure to include a lot more information, like what version of ROS 2 you are using, what version of Autoware you are using, your operating system, and the commands you used to try to compile.  That should get you a lot more help.

**Comment by zazgf** [comment]
Thanks,I will follow these guidelines
