### ISSUE TITLE
Add Python generator

### ISSUE THREAD

**Issue by esteve** [ros2/rosidl#67]
- [x] Preliminary Python generator https://github.com/ros2/rosidl/pull/63
- [x] Constraints https://github.com/ros2/rosidl/pull/65
- [x] Defaults https://github.com/ros2/rosidl/pull/69
- [x] Support nested messages https://github.com/ros2/rosidl/pull/113 https://github.com/ros2/rosidl/pull/119
- [ ] Services

**Comment by esteve** [comment]
This is just a ticket to aggregate all the Python related PRs.

**Comment by mikaelarguedas** [comment]
@ros2/team I think the related PRs are ready for a first round of review. Every feedback is welcome. Timers and guard_conditions will be submitted in a separate PR.

**Comment by mikaelarguedas** [comment]
NOTE: the new functions are not documented yet, the goal of submitting this for review is to get a feature / API approval before documenting it
