### ISSUE TITLE
Retrieve interfaces files from sources

### ISSUE THREAD

**Issue by RollFroy** [ros2/rosidl#719]
Hello,

Is there a way to generate interfaces files from sources files (C or C++) ?

Thanks,
Roll'Froy

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
