### ISSUE TITLE
Clean up import logic in rosidl_generator_py

### ISSUE THREAD

**Issue by esteve** [ros2/rosidl#92]
See #83 #90 #91

**Comment by dirk-thomas** [comment]
Please also address the comments from #74.

**Comment by mikaelarguedas** [comment]
@dirk-thomas @wjwwood do you know what there is still to do on this issue ?

**Comment by dirk-thomas** [comment]
Beside the comments from #74 (which you have just addressed) I don't know what else this refers to. I would suggest to close and request feedback.

**Comment by mikaelarguedas** [comment]
Sounds good, closing this then.
@wjwwood and @esteve if you happen to remember if anything else needs to be done here, feel free to comment on / reopen this issue
