### ISSUE TITLE
Look into generating only one Python library per message package

### ISSUE THREAD

**Issue by esteve** [ros2/rosidl#96]
This may reduce compilation time and also simplify our CMake scripts.

**Comment by dirk-thomas** [comment]
Are you referring to one library which contains the typesupport for multiple rmw implementation?

**Comment by esteve** [comment]
Yes, right now we build one library per message per typesupport impl, I'm working on building only one per package per typesupport impl.

**Comment by dirk-thomas** [comment]
Ok, so N libraries for N rmw implementation which each contain typesupport for all messages of the package. That would indeed be great.
