### ISSUE TITLE
build fails when only building FastRTPS

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rosidl#99]
http://ci.ros2.org/job/ci_windows/1092/

@esteve Can you please take a look at this since it seems to be related to the Python message generator.

**Comment by jacquelinekay** [comment]
I believe this will be fixed by ros2/rosidl#95. Can you review?

**Comment by dirk-thomas** [comment]
I triggered http://ci.ros2.org/job/ci_windows/1096/ using the branch of that PR.

**Comment by jacquelinekay** [comment]
The CI job built. There are some Python test failures which look unrelated.

**Comment by dirk-thomas** [comment]
With the referenced PR it at least passes the build step. But it still fails some Python related tests which shouldn't happen when only selecting FastRTPS.

**Comment by jacquelinekay** [comment]
Good point. I haven't looked very carefully at the structure of rosidl_generator_py/rclpy but this line seems to be a problem:

https://github.com/ros2/rclpy/blob/master/rclpy/rclpy/__init__.py#L15

Shouldn't the middleware name be parameterized at least? Does rclpy only ever use Opensplice TS?
